/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './*.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        tertiary: '#003d27',
        'surface-tint': '#3755c3',
        'outline-variant': '#c4c5d5',
        'on-surface': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#001453',
        surface: '#f7f9fb',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed': '#e1e0ff',
        'tertiary-fixed': '#6ffbbe',
        'on-tertiary-fixed': '#002113',
        'surface-container': '#eceef0',
        secondary: '#4648d4',
        'on-secondary-container': '#fffbff',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#c0c1ff',
        'surface-variant': '#e0e3e5',
        'on-secondary-fixed': '#07006c',
        'on-background': '#191c1e',
        'inverse-primary': '#b8c4ff',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        primary: '#00288e',
        'on-surface-variant': '#444653',
        'on-secondary-fixed-variant': '#2f2ebe',
        'on-tertiary-container': '#3fd298',
        'on-primary-fixed-variant': '#173bab',
        'primary-container': '#1e40af',
        'primary-fixed-dim': '#b8c4ff',
        'surface-dim': '#d8dadc',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed-variant': '#005236',
        'secondary-container': '#6063ee',
        'inverse-surface': '#2d3133',
        'surface-bright': '#f7f9fb',
        background: '#f7f9fb',
        'on-primary-container': '#a8b8ff',
        outline: '#757684',
        error: '#ba1a1a',
        'surface-container-high': '#e6e8ea',
        'tertiary-container': '#00563a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dde1ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        bento: '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
